wordle:
  stage: deploy
  script:
    - emcc -O3 -s WASM=1 -s "EXPORTED_RUNTIME_METHODS=['cwrap']" api.cpp
    - cp index.html ${TENCENT_WORKDING_DIR}/
    - cp a.out.js ${TENCENT_WORKDING_DIR}/
    - cp a.out.wasm ${TENCENT_WORKDING_DIR}/
    - cp assets/* ${TENCENT_WORKDING_DIR}/assets/
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
